// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	app_errors "setmaker-api-go-rest/internal/utils/errors"

	mock "github.com/stretchr/testify/mock"
)

// IAppError is an autogenerated mock type for the IAppError type
type IAppError struct {
	mock.Mock
}

// GetCode provides a mock function with given fields:
func (_m *IAppError) GetCode() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// GetMessage provides a mock function with given fields:
func (_m *IAppError) GetMessage() (interface{}, error) {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPayload provides a mock function with given fields:
func (_m *IAppError) GetPayload() app_errors.ErrorPayload {
	ret := _m.Called()

	var r0 app_errors.ErrorPayload
	if rf, ok := ret.Get(0).(func() app_errors.ErrorPayload); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(app_errors.ErrorPayload)
	}

	return r0
}
